import ItemDisplay from "../components/ItemDisplay";

export const style = {
    navbarContainer: "flex w-full absolute items-center justify-between h-16 bg-[#00684A]  shadow-lg relative top-0",
    navbarLogo: "flex items-center gap-[30px]",
    moreButton: "sm:hidden flex items-center bg-amber-50 rounded-[10px] gap-[4px] py-1 px-1  mr-2.5 flex items-center gap-2 md:hidden cursor-pointer",
    catagoryList: "sm:hidden relative top-[60px] flex flex-col items-center  text-[white] bg-[red] left-[220px]",
    rightSidebarIcon: "md:hidden group relative cursor-pointer ml-2.5",
    lockIcon: "absolute top-17 z-200 left-27 hover:text-[red] mr-2 text-[white]",
    navbarLogoImage: "hidden md:flex p-1.5 h-16 w-16 rounded-full object-cover hover:scale-105 duration-300 cursor-pointer",
    navbarHeaderText: "text-2xl font-bold tracking-wide  text-gray-800 hover:text-pink-500 transition",
    navbarList: " md:flex space-x-8 text-lg font-medium hidden",
    navbarListOpen: "md:block md:flex text-lg font-medium flex flex-col top-15 pt-1 left-0 gap-5 shadow-amber-700 rounded-r-2xl bg-amber-400 z-10  absolute",
    navbarListText: `flex items-center p-2 gap-1 rounded-[10px] m-1.5 hover:text-pink-500 transition hover:scale-105`,
    getStartedButton: "hidden sm:block bg-red-500 mr-3 hover:bg-blue-600 hover:text-red-400 text-white px-4 py-2 hover:rounded-[20px] cursor-pointer",
    chevronDown: "text-lg transition-transform duration-300",
    menuListContainer: "md:hidden w-[30%] absolute top-[55px] right-0 z-10 justify-end bg-white shadow-md rounded-lg mt-2 p-4 animate-slideDown mx-4",
    menuList: "flex flex-col space-y-4 text-center text-gray-800 font-medium",
    menuListText: `hover:text-pink-500 cursor-pointer transition hover:scale-105 py-2`,
    explorMenu: "hidden md:block px-6 md:px-12 py-8",
    exploreMenuHeader: "text-2xl md:text-3xl font-bold text-gray-900 mb-6",
    menusDisplay: "grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-6",
    menuDisplay: "menu-item bg-white rounded-xl shadow-md overflow-hidden cursor-pointer transform transition duration-300 hover:scale-105 hover:shadow-xl",
    menuimage: "w-full h-40 object-cover",
    menuDisplayTextContainer: "p-4 text-center",
    menuDisplayText: "text-gray-800 font-semibold text-lg",
    heroSection: "hero-section relative w-full h-[80vh] sm:w-full max-sm:h-[30vh]",
    heroSectionImage: "absolute inset-0 w-full h-full object-cover",
    heroSectionText: "absolute inset-0 bg-black/40 flex flex-col justify-center items-center text-center px-4",
    heroSectionHeader: "font-bold mb-4 flex flex-wrap justify-center gap-1",
    heroSectionHeaderLetter: `transition-transform duration-300 hover:scale-125 cursor-pointer`,
    heroSectionParagraph: "hidden sm:block text-gray-200 mb-6",
    heroSectionParagraphLetter: `transition-transform duration-300 hover:scale-125 cursor-pointer`,
    heroSectionButton: "bg-[white] hover:bg-[#543218] text-white font-semibold py-3 px-8 rounded-lg transition duration-300",
    heroSectionButtonText: `transition-transform duration-300 hover:scale-125 cursor-pointer`,
    itemDisplayContainer: "py-12 bg-gray-50",
    itemDisplayHeader: "text-3xl sm:text-4xl md:text-5xl font-bold text-center text-gray-900 mb-10",
    itemsDisplay: "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 px-8 md:px-12",
    ItemDisplay: "flex h-full w-full flex-row-reverse  sm:flex-col menu-items bg-white rounded-xl shadow-md overflow-hidden hover:scale-105 transform transition duration-300",
    itemImage: "w-full h-full object-cover",
    itemContainer: "p-4 text-center",
    itemName: "text-lg truncate font-semibold text-gray-800",
    itemDescription: "text-gray-500  mt-1",
    itemPrice: "text-[#6B4226] font-bold mt-2",

    loginPage: "min-h-screen flex items-center justify-center bg-linear-to-r from-pink-400 to-purple-600 px-4",
    loginContainer: "bg-white rounded-xl shadow-lg w-full max-w-md p-8",
    loginHeader: "text-2xl font-bold text-center mb-10 text-gray-800",

    loginForm: "space-y-6",
    loginInputContainer: "space-y-2",
    loginInputEmail: "w-full outline-none text-gray-700",
    rememberMeContainer: "flex items-center justify-between text-sm",
    rememberMeLabel: "flex items-center gap-2 cursor-pointer text-gray-600 hover:text-gray-900",
    rememberMeInput: "w-4 h-4 rounded border-gray-300 text-orange-600 focus:ring-orange-500",
    rememberMeLink: "font-medium text-orange-600 hover:text-orange-700 hover:underline",
    submitButton: "w-full py-3.5 rounded-xl text-white font-bold shadow-lg shadow-orange-500/20 transition-all transform active:scale-95",
    isLoadingOpition: "flex items-center justify-center gap-2",
    loginCrossIcon: "mt-3 cursor-pointer h-[18px]"
};